### ISSUE TITLE
Issue with sq.gr.ligrec in squidpy.

### ISSUE THREAD

**Issue by Rohitarora21** [theislab/squidpy#433] opened 2021-11-23 19:24 UTC
## Description
Issue with using the sq.gr.ligrec function, same error on multiple datasets and haven't been able to get the function to run.
...

## Minimal reproducible example on a sample dataset, the same error occurs on my dataset
import squidpy as sq
adata = sq.datasets.seqfish()
res = sq.gr.ligrec(
    adata,
    n_perms=1000,
    cluster_key="celltype_mapped_refined",
    copy=True,
    use_raw=False,
    transmitter_params={"categories": "ligand"},
    receiver_params={"categories": "receptor"}
)
...
```

## Traceback
TypeError                                 Traceback (most recent call last)
<ipython-input-390-aa53a57fe9bb> in <module>
      1 #ligand receptor analysis using squidpy
      2 adata = sq.datasets.seqfish()
----> 3 res = sq.gr.ligrec(
      4     adata,
      5     n_perms=1000,

~\anaconda3\lib\site-packages\squidpy\gr\_ligrec.py in ligrec(adata, cluster_key, interactions, complex_policy, threshold, corr_method, corr_axis, use_raw, copy, key_added, gene_symbols, **kwargs)
    642     with _genesymbols(adata, key=gene_symbols, use_raw=use_raw, make_unique=False):
    643         return (  # type: ignore[no-any-return]
--> 644             PermutationTest(adata, use_raw=use_raw)
    645             .prepare(interactions, complex_policy=complex_policy, **kwargs)
    646             .test(

~\anaconda3\lib\site-packages\squidpy\gr\_ligrec.py in prepare(self, interactions, complex_policy, interactions_params, transmitter_params, receiver_params, **_)
    584 
    585             start = logg.info("Fetching interactions from `omnipath`")
--> 586             interactions = import_intercell_network(
    587                 interactions_params=interactions_params,
    588                 transmitter_params=transmitter_params,

~\anaconda3\lib\site-packages\omnipath\_core\requests\interactions\_utils.py in import_intercell_network(include, interactions_params, transmitter_params, receiver_params)
    100     receiver_params.setdefault("scope", "generic")
    101 
--> 102     interactions = AllInteractions.get(include=include, **interactions_params)
    103     if interactions.empty:
    104         raise ValueError(_ERROR_EMPTY_FMT.format(obj="interactions"))

~\anaconda3\lib\site-packages\omnipath\_core\requests\_utils.py in wrapper(wrapped, _instance, args, kwargs)
    102     @wrapt.decorator(adapter=wrapt.adapter_factory(argspec_factory))
    103     def wrapper(wrapped, _instance, args, kwargs):
--> 104         return wrapped(*args, **kwargs)
    105 
    106     if hasattr(clazz, "get") and not hasattr(clazz.get, "__wrapped__"):

~\anaconda3\lib\site-packages\omnipath\_core\requests\interactions\_interactions.py in get(cls, include, exclude, **kwargs)
    375         %(get.returns)s
    376         """
--> 377         return cls(include, exclude=exclude)._get(**kwargs)
    378 
    379 

~\anaconda3\lib\site-packages\omnipath\_core\requests\interactions\_interactions.py in __init__(self, include, exclude)
    338         exclude: Optional[Datasets_t] = None,
    339     ):
--> 340         super().__init__(include, exclude=exclude)
    341 
    342     def _inject_fields(self, params: Dict[str, Any]) -> Dict[str, Any]:

~\anaconda3\lib\site-packages\omnipath\_core\requests\interactions\_interactions.py in __init__(self, datasets, exclude)
     66         exclude: Optional[Datasets_t] = None,
     67     ):
---> 68         super().__init__()
     69 
     70         datasets = _to_dataset_set(datasets, "datasets", set(InteractionDataset))

~\anaconda3\lib\site-packages\omnipath\_core\requests\_request.py in __init__(self)
     74 
     75     def __init__(self):
---> 76         self._downloader = Downloader(options)
     77 
     78     @classmethod

~\anaconda3\lib\site-packages\omnipath\_core\downloader\_downloader.py in __init__(self, opts)
     47         if self._options.num_retries > 0:
     48             adapter = HTTPAdapter(
---> 49                 max_retries=Retry(
     50                     total=self._options.num_retries,
     51                     redirect=5,

TypeError: __init__() got an unexpected keyword argument 'allowed_methods'


## Version
sq version: 1.1.2
omnipath version: 1.0.5

**Comment by michalk8** [comment] 2021-11-23 23:30
Hi @Rohitarora21 ,

this is more of a ``omnipath`` issue; what's your ``urllib3`` version? It requires ``urllib3>=1.26.0``.

**Comment by Rohitarora21** [comment] 2021-11-24 01:20
Hi @michalk8 thanks after upgrading the package version it seems to have progressed further this time, but now I'm running into this bug with the same code as above:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-58bec6b89f26> in <module>
----> 1 res = sq.gr.ligrec(
      2     adata,
      3     n_perms=1000,
      4     cluster_key="celltype_mapped_refined",
      5     copy=True,

~\anaconda3\lib\site-packages\squidpy\gr\_ligrec.py in ligrec(adata, cluster_key, interactions, complex_policy, threshold, corr_method, corr_axis, use_raw, copy, key_added, gene_symbols, **kwargs)
    642     with _genesymbols(adata, key=gene_symbols, use_raw=use_raw, make_unique=False):
    643         return (  # type: ignore[no-any-return]
--> 644             PermutationTest(adata, use_raw=use_raw)
    645             .prepare(interactions, complex_policy=complex_policy, **kwargs)
    646             .test(

~\anaconda3\lib\site-packages\squidpy\gr\_ligrec.py in prepare(self, interactions, complex_policy, interactions_params, transmitter_params, receiver_params, **_)
    606             interactions[TARGET] = interactions[TARGET].str.replace("^COMPLEX:", "", regex=True)
    607 
--> 608         _ = super().prepare(interactions, complex_policy=complex_policy)
    609         return self
    610 

~\anaconda3\lib\site-packages\squidpy\gr\_ligrec.py in prepare(self, interactions, complex_policy)
    287             logg.warning(f"Removed `{n_genes_prior - self._data.shape[1]}` duplicate gene(s)")
    288 
--> 289         self._filter_interactions_complexes(complex_policy)
    290         self._filter_interactions_by_genes()
    291         self._trim_data()

~\anaconda3\lib\site-packages\squidpy\gr\_ligrec.py in _filter_interactions_complexes(self, complex_policy)
    509         if complex_policy == ComplexPolicy.MIN:
    510             logg.debug("DEBUG: Selecting genes from complexes based on minimum average expression")
--> 511             self.interactions[SOURCE] = self.interactions[SOURCE].apply(find_min_gene_in_complex)
    512             self.interactions[TARGET] = self.interactions[TARGET].apply(find_min_gene_in_complex)
    513         elif complex_policy == ComplexPolicy.ALL:

~\anaconda3\lib\site-packages\pandas\core\series.py in apply(self, func, convert_dtype, args, **kwds)
   4136             else:
   4137                 values = self.astype(object)._values
-> 4138                 mapped = lib.map_infer(values, f, convert=convert_dtype)
   4139 
   4140         if len(mapped) and isinstance(mapped[0], Series):

pandas\_libs\lib.pyx in pandas._libs.lib.map_infer()

~\anaconda3\lib\site-packages\squidpy\gr\_ligrec.py in find_min_gene_in_complex(_complex)
    491 
    492         def find_min_gene_in_complex(_complex: str) -> str | None:
--> 493             if "_" not in _complex:
    494                 return _complex
    495             complexes = [c for c in _complex.split("_") if c in self._data.columns]

TypeError: argument of type 'NoneType' is not iterable

**Comment by michalk8** [comment] 2021-11-24 17:13
Hmm, this shouldn't really happen, can you post the output of the following:
```python
from omnipath.interactions import import_intercell_network
from omnipath import clear_cache

clear_cache()
df = import_intercell_network(transmitter_params={"categories": "ligand"}, receiver_params={"categories": "receptor"})

print(df['source'].isnull().sum())  # should print 0
```
and afterward try re-running the `squidpy.gr.ligrec` function? Afaik it should always be a string, if not, will do an extra check.

**Comment by Rohitarora21** [comment] 2021-11-24 19:33
![image](https://user-images.githubusercontent.com/45678919/143302402-13547e87-8d3b-4285-ba6f-0488992d136c.png)

Following this, I re-ran the squidpy.gr.ligrec function and ended up with the same output:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-58bec6b89f26> in <module>
----> 1 res = sq.gr.ligrec(
      2     adata,
      3     n_perms=1000,
      4     cluster_key="celltype_mapped_refined",
      5     copy=True,

~\anaconda3\lib\site-packages\squidpy\gr\_ligrec.py in ligrec(adata, cluster_key, interactions, complex_policy, threshold, corr_method, corr_axis, use_raw, copy, key_added, gene_symbols, **kwargs)
    642     with _genesymbols(adata, key=gene_symbols, use_raw=use_raw, make_unique=False):
    643         return (  # type: ignore[no-any-return]
--> 644             PermutationTest(adata, use_raw=use_raw)
    645             .prepare(interactions, complex_policy=complex_policy, **kwargs)
    646             .test(

~\anaconda3\lib\site-packages\squidpy\gr\_ligrec.py in prepare(self, interactions, complex_policy, interactions_params, transmitter_params, receiver_params, **_)
    606             interactions[TARGET] = interactions[TARGET].str.replace("^COMPLEX:", "", regex=True)
    607 
--> 608         _ = super().prepare(interactions, complex_policy=complex_policy)
    609         return self
    610 

~\anaconda3\lib\site-packages\squidpy\gr\_ligrec.py in prepare(self, interactions, complex_policy)
    287             logg.warning(f"Removed `{n_genes_prior - self._data.shape[1]}` duplicate gene(s)")
    288 
--> 289         self._filter_interactions_complexes(complex_policy)
    290         self._filter_interactions_by_genes()
    291         self._trim_data()

~\anaconda3\lib\site-packages\squidpy\gr\_ligrec.py in _filter_interactions_complexes(self, complex_policy)
    509         if complex_policy == ComplexPolicy.MIN:
    510             logg.debug("DEBUG: Selecting genes from complexes based on minimum average expression")
--> 511             self.interactions[SOURCE] = self.interactions[SOURCE].apply(find_min_gene_in_complex)
    512             self.interactions[TARGET] = self.interactions[TARGET].apply(find_min_gene_in_complex)
    513         elif complex_policy == ComplexPolicy.ALL:

~\anaconda3\lib\site-packages\pandas\core\series.py in apply(self, func, convert_dtype, args, **kwds)
   4136             else:
   4137                 values = self.astype(object)._values
-> 4138                 mapped = lib.map_infer(values, f, convert=convert_dtype)
   4139 
   4140         if len(mapped) and isinstance(mapped[0], Series):

pandas\_libs\lib.pyx in pandas._libs.lib.map_infer()

~\anaconda3\lib\site-packages\squidpy\gr\_ligrec.py in find_min_gene_in_complex(_complex)
    491 
    492         def find_min_gene_in_complex(_complex: str) -> str | None:
--> 493             if "_" not in _complex:
    494                 return _complex
    495             complexes = [c for c in _complex.split("_") if c in self._data.columns]

TypeError: argument of type 'NoneType' is not iterable

**Comment by michalk8** [comment] 2021-11-24 21:43
Thanks for catching this, should be fixed now on `dev` - you can try installing it as `pip install git+https://github.com/theislab/squidpy@dev`.

**Comment by TheAustinator** [comment] 2022-01-30 08:21
Hey @michalk8, I'm hitting the same issue on 1.1.3.dev15+g2d8dfed. Here's my `pip list`
```
Package                           Version              Location                     
--------------------------------- -------------------- -----------------------------
absl-py                           1.0.0                
adjustText                        0.7.3                
aiohttp                           3.8.1                
aiosignal                         1.2.0                
airr                              1.3.1                
alabaster                         0.7.12               
amqp                              5.0.9                
analysaurus                       0.0.1                /home/ubuntu/code/analysaurus
aniso8601                         9.0.1                
anndata                           0.7.8                
anndata2ri                        1.0.6                
annoy                             1.17.0               
ansi2html                         1.6.0                
anyio                             3.5.0                
appdirs                           1.4.4                
arboreto                          0.1.6                
argon2-cffi                       21.3.0               
argon2-cffi-bindings              21.2.0               
arrow                             1.2.2                
asciitree                         0.3.3                
asgiref                           3.5.0                
astroid                           2.9.3                
astunparse                        1.6.3                
async-timeout                     4.0.2                
attrs                             21.4.0               
autopep8                          1.6.0                
Babel                             2.9.1                
backcall                          0.2.0                
backports.zoneinfo                0.2.1                
batchglm                          0.7.4                
bbknn                             1.5.1                
beautifulsoup4                    4.10.0               
billiard                          3.6.4.0              
binaryornot                       0.4.4                
biopython                         1.79                 
bioservices                       1.8.3                
black                             21.12b0              
bleach                            4.1.0                
bokeh                             2.4.2                
boltons                           21.0.0               
boto3                             1.20.29              
botocore                          1.23.29              
Brotli                            1.0.9                
bs4                               0.0.1                
cachetools                        4.2.4                
cachey                            0.2.1                
cattrs                            1.10.0               
celery                            5.2.3                
cellforest                        0.0.2                /home/ubuntu/code/cellforest 
cellxgene                         1.0.0                
certifi                           2019.11.28           
cffi                              1.15.0               
chardet                           3.0.4                
charset-normalizer                2.0.10               
click                             8.0.3                
click-didyoumean                  0.3.0                
click-plugins                     1.1.1                
click-repl                        0.2.0                
cloudpickle                       2.0.0                
cmake                             3.22.2               
colorama                          0.4.4                
coloredlogs                       15.0.1               
colorlog                          6.6.0                
colormath                         3.0.0                
commonmark                        0.9.1                
ConfigArgParse                    1.5.3                
configparser                      5.2.0                
cookiecutter                      1.7.3                
crossref-commons                  0.0.7                
ctxcore                           0.1.1                
cycler                            0.11.0               
Cython                            0.29.27              
cytoolz                           0.11.2               
dash                              2.0.0                
dash-building-blocks              0.1.2                
dash-core-components              2.0.0                
dash-cytoscape                    0.3.0                
dash-html-components              2.0.0                
dash-table                        5.0.0                
dask                              2021.12.0            
dask-image                        2021.12.0            
dataforest                        0.0.2                /home/ubuntu/code/dataforest 
dbus-python                       1.2.16               
debugpy                           1.5.1                
decorator                         5.1.0                
defusedxml                        0.7.1                
diffxpy                           0.7.4                
dill                              0.3.4                
distributed                       2021.12.0            
distro-info                       0.23ubuntu1          
Django                            3.2.10               
django-crispy-forms               1.14.0               
django-extensions                 3.1.5                
django-filter                     21.1                 
django-js-asset                   1.2.2                
django-markdownify                0.9.0                
django-mptt                       0.13.4               
django-widget-tweaks              1.4.12               
djangorestframework               3.13.1               
djangorestframework-datatables    0.7.0                
docrep                            0.3.2                
docstring-parser                  0.13                 
docutils                          0.17.1               
dunamai                           1.8.0                
easydev                           0.12.0               
entrypoints                       0.3                  
enum-tools                        0.8.0                
et-xmlfile                        1.1.0                
fa2                               0.3.5                
fastcluster                       1.2.4                
fastcore                          1.3.27               
fasteners                         0.17.3               
fbpca                             1.0                  
flake8                            4.0.1                
flasgger                          0.9.5                
Flask                             2.0.2                
Flask-Compress                    1.10.1               
Flask-Cors                        3.0.10               
Flask-RESTful                     0.3.9                
flask-server-timing               0.1.2                
flask-talisman                    0.8.1                
flatbuffers                       1.12                 
flatten-dict                      0.4.2                
fonttools                         4.28.5               
fpdf                              1.7.2                
freetype-py                       2.2.0                
frozendict                        2.1.3                
frozenlist                        1.2.0                
fsspec                            0.7.4                
future                            0.18.2               
fuzzywuzzy                        0.18.0               
gast                              0.4.0                
GDAL                              3.0.4                
geosketch                         1.2                  
get-version                       3.5.3                
gevent                            21.12.0              
gitdb                             4.0.9                
GitPython                         3.1.26               
google-auth                       2.3.3                
google-auth-oauthlib              0.4.6                
google-pasta                      0.2.0                
gprofiler-official                1.0.0                
greenlet                          1.1.2                
grequests                         0.6.0                
grpcio                            1.43.0               
gsea-api                          0.3.4                
gseapy                            0.10.7               
gunicorn                          20.1.0               
h5py                              2.10.0               
harmonypy                         0.0.5                
HeapDict                          1.0.1                
hsluv                             5.0.2                
humanfriendly                     10.0                 
idna                              2.8                  
igraph                            0.9.8                
imageio                           2.14.1               
imagesize                         1.3.0                
importlib-metadata                4.10.0               
importlib-resources               5.4.0                
inflect                           5.3.0                
iniconfig                         1.1.1                
interlap                          0.2.7                
intervaltree                      2.1.0                
ipdb                              0.13.9               
ipykernel                         6.6.1                
ipympl                            0.8.5                
ipython                           7.31.0               
ipython-genutils                  0.2.0                
ipywidgets                        7.6.5                
isort                             5.10.1               
iterativeWGCNA                    1.1.6                
itsdangerous                      2.0.1                
jedi                              0.18.1               
Jinja2                            3.0.3                
jinja2-time                       0.2.0                
jmespath                          0.10.0               
joblib                            0.17.0               
json5                             0.9.6                
jsonschema                        4.3.3                
jupyter-client                    7.1.0                
jupyter-core                      4.9.1                
jupyter-dash                      0.4.0                
jupyter-helpers                   0.2.3                
jupyter-lsp                       1.5.1                
jupyter-server                    1.13.4               
jupyter-server-mathjax            0.2.3                
jupyterlab                        3.2.8                
jupyterlab-code-formatter         1.4.10               
jupyterlab-git                    0.34.2               
jupyterlab-lsp                    3.10.0               
jupyterlab-pygments               0.1.2                
jupyterlab-server                 2.10.3               
jupyterlab-templates              0.3.1                
jupyterlab-widgets                1.0.2                
jupytext                          1.13.6               
keras                             2.7.0                
Keras-Preprocessing               1.1.2                
kiwisolver                        1.3.2                
kombu                             5.2.3                
lazy-import                       0.2.2                
lazy-object-proxy                 1.7.1                
lckr-jupyterlab-variableinspector 3.0.9                
leidenalg                         0.8.8                
libclang                          13.0.0               
llvmlite                          0.37.0               
locket                            0.2.1                
loompy                            3.0.6                
louvain                           0.7.1                
lxml                              4.7.1                
lzstring                          1.0.4                
magicgui                          0.3.4                
Markdown                          3.3.6                
markdown-it-py                    1.1.0                
MarkupSafe                        2.0.1                
matplotlib                        3.5.1                
matplotlib-inline                 0.1.3                
mccabe                            0.6.1                
mdit-py-plugins                   0.3.0                
mistune                           0.8.4                
msgpack                           1.0.3                
multidict                         5.2.0                
multiprocessing-on-dill           3.5.0a4              
multiqc                           1.11                 
mypy-extensions                   0.4.3                
napari                            0.4.13               
napari-console                    0.0.4                
napari-plugin-engine              0.2.0                
napari-svg                        0.1.6                
natsort                           8.0.2                
nbclassic                         0.3.5                
nbclient                          0.5.9                
nbconvert                         6.4.0                
nbdime                            3.1.1                
nbformat                          5.1.3                
nbresuse                          0.4.0                
neo4j                             4.4.1                
nest-asyncio                      1.5.4                
networkx                          2.6.3                
notebook                          6.4.6                
npe2                              0.1.2                
numba                             0.54.1               
numcodecs                         0.9.1                
numexpr                           2.8.1                
numpy                             1.17.4               
numpy-groupies                    0.9.14               
numpydoc                          1.2                  
oauthlib                          3.1.1                
obonet                            0.3.0                
omnipath                          1.0.3                
openpyxl                          3.0.9                
opt-einsum                        3.3.0                
Owlready2                         0.36                 
packaging                         21.3                 
pandas                            1.2.5                
pandocfilters                     1.5.0                
parasail                          1.2.4                
parso                             0.8.3                
partd                             1.2.0                
passlib                           1.7.4                
path                              16.2.0               
pathlib                           1.0.1                
pathspec                          0.9.0                
patsy                             0.5.2                
peepdis                           0.1.13               
pexpect                           4.8.0                
PhenoGraph                        1.5.7                
pickleshare                       0.7.5                
Pillow                            9.0.0                
PIMS                              0.5                  
Pint                              0.18                 
pip                               20.0.2               
platformdirs                      2.4.1                
plotly                            5.5.0                
pluggy                            1.0.0                
poyo                              0.5.0                
prometheus-client                 0.12.0               
prompt-toolkit                    3.0.24               
protobuf                          3.19.1               
psutil                            5.9.0                
psycopg2                          2.9.3                
psygnal                           0.2.0                
ptvsd                             4.3.2                
ptyprocess                        0.7.0                
py                                1.11.0               
pyarrow                           0.16.0               
pyasn1                            0.4.8                
pyasn1-modules                    0.2.8                
pybiomart                         0.2.0                
pycodestyle                       2.8.0                
pycparser                         2.21                 
pydantic                          1.9.0                
pyDeprecate                       0.3.0                
pydocstyle                        6.1.1                
pyflakes                          2.4.0                
Pygments                          2.11.1               
PyGObject                         3.36.0               
PyHGNC                            0.2.4                
pylint                            2.12.2               
PyMySQL                           1.0.2                
pynndescent                       0.5.5                
PyOpenGL                          3.1.5                
pyparsing                         3.0.6                
PyQt5                             5.15.6               
PyQt5-Qt5                         5.15.2               
PyQt5-sip                         12.9.0               
pyro-api                          0.1.2                
pyro-ppl                          1.8.0                
pyrsistent                        0.18.0               
pysam                             0.18.0               
pyscenic                          0.11.2               
pytest                            6.2.5                
python-apt                        2.0.0+ubuntu0.20.4.6 
python-dateutil                   2.8.2                
python-debian                     0.1.36ubuntu1        
python-igraph                     0.9.8                
python-Levenshtein                0.12.2               
python-lsp-jsonrpc                1.0.0                
python-lsp-server                 1.3.3                
python-slugify                    5.0.2                
pytoml                            0.1.21               
pytomlpp                          1.0.10               
pytorch-lightning                 1.3.1                
pytz                              2021.3               
pytz-deprecation-shim             0.1.0.post0          
PyWavelets                        1.2.0                
PyYAML                            5.4.1                
pyzmq                             22.3.0               
qtconsole                         5.2.2                
QtPy                              2.0.0                
questionary                       1.10.0               
ratelimit                         2.2.1                
requests                          2.22.0               
requests-cache                    0.9.1                
requests-oauthlib                 1.3.0                
requests-unixsocket               0.2.0                
retrying                          1.3.3                
rich                              10.16.2              
rope                              0.22.0               
rpy2                              3.4.2                
rsa                               4.8                  
s3fs                              0.4.2                
s3transfer                        0.5.0                
scanorama                         1.7.1                
scanpy                            1.8.2                
scikit-image                      0.19.1               
scikit-learn                      1.0.2                
scikit-misc                       0.1.4                
scipy                             1.7.3                
scirpy                            0.10.1               
scrublet                          0.2.3                
scvi-tools                        0.14.5               
seaborn                           0.11.2               
Send2Trash                        1.8.0                
setuptools                        45.2.0               
setuptools-scm                    6.4.2                
sfaira                            0.3.9                
sidecar                           0.5.1                
simplejson                        3.17.6               
sinfo                             0.3.4                
six                               1.14.0               
slicerator                        1.0.0                
smmap                             5.0.0                
sniffio                           1.2.0                
snowballstemmer                   2.2.0                
solo-sc                           1.2                  /source/solo                 
sortedcontainers                  2.4.0                
soupsieve                         2.3.1                
sparse                            0.13.0               
spectra                           0.0.11               
Sphinx                            4.4.0                
sphinxcontrib-applehelp           1.0.2                
sphinxcontrib-devhelp             1.0.2                
sphinxcontrib-htmlhelp            2.0.0                
sphinxcontrib-jsmath              1.0.1                
sphinxcontrib-qthelp              1.0.3                
sphinxcontrib-serializinghtml     1.1.5                
SQLAlchemy                        1.4.31               
sqlparse                          0.4.2                
squarify                          0.4.3                
squidpy                           1.1.3.dev15+g2d8dfed 
statsmodels                       0.13.1               
stdlib-list                       0.8.0                
suds-community                    1.0.0                
superqt                           0.2.5.post1          
switchlang                        0.1.0                
tables                            3.7.0                
tblib                             1.7.0                
tenacity                          8.0.1                
tensorboard                       2.7.0                
tensorboard-data-server           0.6.1                
tensorboard-plugin-wit            1.8.1                
tensorflow                        2.7.0                
tensorflow-estimator              2.7.0                
tensorflow-io-gcs-filesystem      0.23.1               
termcolor                         1.1.0                
terminado                         0.12.1               
testpath                          0.5.0                
text-unidecode                    1.3                  
texttable                         1.6.4                
threadpoolctl                     3.0.0                
tifffile                          2021.11.2            
toml                              0.10.2               
tomli                             1.2.3                
toolz                             0.11.2               
torch                             1.10.1               
torchmetrics                      0.6.2                
tornado                           6.1                  
tqdm                              4.62.3               
traitlets                         5.1.1                
trimap                            1.0.15               
typeguard                         2.13.3               
typer                             0.4.0                
typing-extensions                 4.0.1                
tzdata                            2021.5               
tzlocal                           4.1                  
ujson                             5.1.0                
umap-learn                        0.5.2                
unattended-upgrades               0.1                  
url-normalize                     1.4.3                
urllib3                           1.25.8               
versioneer                        0.21                 
vine                              5.0.0                
vispy                             0.9.4                
wcwidth                           0.2.5                
webencodings                      0.5.1                
websocket-client                  1.2.3                
Werkzeug                          2.0.2                
wheel                             0.34.2               
widgetsnbextension                3.5.2                
wrapt                             1.13.3               
WTForms                           3.0.1                
xarray                            0.21.0               
xeus-python                       0.13.6               
xeus-python-shell                 0.2.0                
xlrd                              1.2.0                
xmltodict                         0.12.0               
yamlordereddictloader             0.4.0                
yapf                              0.32.0               
yarl                              1.7.2                
zarr                              2.10.3               
zict                              2.0.0                
zipp                              3.7.0                
zope.event                        4.5.0                
zope.interface                    5.4.0
```

**Comment by michalk8** [comment] 2022-01-31 16:28
> Hey @michalk8, I'm hitting the same issue on 1.1.3.dev15+g2d8dfed. Here's my pip list

This is worrying, `g2d8dfed` should be after the commit that was supposed to fix this.

**Comment by michalk8** [comment] 2022-02-12 21:26
> This is worrying, g2d8dfed should be after the commit that was supposed to fix this.

I've had a chance to look at this again, using the most recent `dev` https://github.com/theislab/squidpy/commit/075a09b14f9da6dd7f5be51204eba575a91b5dbf
I cannot reproduce this using:
```python3
import squidpy as sq
from omnipath.interactions import import_intercell_network
from omnipath import clear_cache

clear_cache()
df = import_intercell_network(transmitter_params={"categories": "ligand"},
                              receiver_params={"categories": "receptor"})

# mimic what's done in the code
df['source'] = df['genesymbol_intercell_source']
df['target'] = df['genesymbol_intercell_target']
print(df['source'].isnull().sum(), df['target'].isnull().sum())  #should print: 1 0

t = sq.gr._ligrec.PermutationTest(adata, use_raw=False)
t.prepare(df)
```
or by forcibly injecting `None/np.nan/pd.NA/pd.NaT` into `source/target` in the code, so #434 must've fixed this (furthermore support by [test](https://github.com/theislab/squidpy/blob/dev/tests/graph/test_ligrec.py#L454-L459) that was added there).

@TheAustinator not sure why it failed for you I'd suggest using the latest `dev` branch and see if it persists, but in the meantime, I will close this.

**Closed by michalk8** 2022-02-12 21:26 UTC

**Comment by wangjiawen2013** [comment] 2022-04-05 02:04
Hi,
I cannot install squidpy development version, who can give some help?
(spatial) [xxxxxx@localhost squidpy]$ pip install git+https://github.com/theislab/squidpy@dev
Collecting git+https://github.com/theislab/squidpy@dev
  Cloning https://github.com/theislab/squidpy (to revision dev) to /home/wangjw/data/temp/pip-req-build-rv0h1vhq
  Running command git clone -q https://github.com/theislab/squidpy /home/wangjw/data/temp/pip-req-build-rv0h1vhq
  WARNING: Did not find branch or tag 'dev', assuming revision or ref.
  Running command git checkout -q dev
  error: pathspec 'dev' did not match any file(s) known to git.
WARNING: Discarding git+https://github.com/theislab/squidpy@dev. Command errored out with exit status 1: git checkout -q dev Check the logs for full command output.
ERROR: Command errored out with exit status 1: git checkout -q dev Check the logs for full command output.

**Comment by michalk8** [comment] 2022-04-05 11:05
Hi @wangjiawen2013 , `dev` branch as removed, everything development is on `master`.
Could you please try running:
```bash
pip install git+https://github.com/theislab/squidpy@master
```

**Comment by mav-mit** [comment] 2022-04-13 22:58
I got the same issue today on google Colab. 
Tried installing from master branch too.

Here's my pip list. Any suggestions? 
Thanks in advance :) 
[220413_pip_list.txt](https://github.com/theislab/squidpy/files/8485101/220413_pip_list.txt)

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-104-c7cd6c29a993>](https://ukp97v769di-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220412-060046-RC00_441141632#) in <module>()
      8     key_added='cellphoneDB',
      9     show_progress_bar=True,
---> 10     alpha=1e-4
     11     )

8 frames
[/usr/local/lib/python3.7/dist-packages/omnipath/_core/downloader/_downloader.py](https://ukp97v769di-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220412-060046-RC00_441141632#) in __init__(self, opts)
     52                     # allowed_methods=["HEAD", "GET", "OPTIONS"],
     53                     status_forcelist=[413, 429, 500, 502, 503, 504],
---> 54                     backoff_factor=1,
     55                 )
     56             )

TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
```

**Comment by michalk8** [comment] 2022-04-13 23:53
Hi @mav-mit ,
this is related to https://github.com/saezlab/omnipath/issues/18 and was fixed in https://github.com/saezlab/omnipath/pull/19.
I haven't made a new `omnipath` release yet; in the meantime you can try running:
```pip install "urllib3>=1.26.0"```.

**Comment by mav-mit** [comment] 2022-04-14 13:21
All set! Thanks @michalk8
